baseURL = "https://wangjun521.github.io"
languageCode = "zh-cn"
title = "青山几重的博客"
hasCJKLanguage = true # 开启可以让「字数统计」统计汉字
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    since = 2017
    author = "青山几重"                           # Author's name
    avatar = "/images/me/avatar.jpeg"           # Author's avatar
    subtitle = "just a little"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""
    enableGitalk = true

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    # GitHub = "xxoo"
    # Email = "xxoo"
    # Wechat = "/images/me/wechat.png"  # Wechat QRcode image

[params.gitalk]
    clientID = "8a2eee0576ce107588f1" # Your client ID
    clientSecret = "37209f0bb49e03718d307a6d6f8a4f1c37a33d2c" # Your client secret
    repo = "wangjun521.github.io" # The repo to store comments
    owner = "wangjun521" # Your GitHub ID
    admin= "wangjun521" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= false # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.


